name: CI
on:
  workflow_dispatch:
env:
  IMAGE_NAME: node-app-dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          #tags: ${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
            
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with: 
          token: ${{ secrets.PAT }}
          repository: ${{ github.actor }}/argocd-node-app-config
          event-type: new-image
          client-payload: '{"image": "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}"}'








          
          
       
      
      
  
